version: '3'
services:
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: j_worktask_db
    networks:
      my_network:
        ipv4_address: 172.20.0.12
    # ports:
    #   - 3306:3306
    volumes:
      - ./j_worktask_script.sql/docker-entrypoint-initdb.d/j_worktask_script.sql
  backend:
    build:
      context: ./serverjwt
      dockerfile: dockerfile
      # ports:
      #   - 6001:3000
    networks:
      my_network:
        ipv4_address: 172.20.0.11
    restart: on-failure
    environment:
      # Aqui setamos nossas variáveis de ambiente - não se preocupe, mais para frente, ainda nesse dia, temos
      # uma seção inteira destinada a explicá-las!
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      - database

  frontend:
    build:
      context: ./clientjwt
      dockerfile: dockerfile
    restart: on-failure
    # ports:
    #   - 4455:5173
    networks:
      my_network:
        ipv4_address: 172.20.0.10
    #command: npm start

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
