version: '3'
services:
  backend:
    build:
      context: ./serverjwt
      dockerfile: dockerfile
    networks:
      my_network:
        ipv4_address: 172.20.0.11
    restart: on-failure
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      - database
  frontend:
    build:
      context: ./clientjwt
      dockerfile: dockerfile
    restart: on-failure
    networks:
      my_network:
        ipv4_address: 172.20.0.10
  database:
    image: mysql:8.0.29
    restart: always
    ports:
      # Expõe a porta padrão do banco de dados
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: j_worktask_db
    networks:
      my_network:
        ipv4_address: 172.20.0.12
    volumes:
      - ./j_worktask_script.sql:/docker-entrypoint-initdb.d/j_worktask_script.sql
    command:
      [
        "--init-file",
        "/docker-entrypoint-initdb.d/j_worktask_script.sql"
      ]
networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
